plugins:
  - serverless-offline
service: serverless-reporting-dashboard
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::automate-tests-reports'
        - 'arn:aws:s3:::automate-tests-reports/*'

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /dashboard
          method: GET
      - http:
          path: /{execution+}
          method: GET
