# plugins:
#   - serverless-offline
# service: sample-app
# provider:
#   name: aws
#   runtime: nodejs12.x
#   stage: dev
#   region: us-east-1
#   memorySize: 128
#   iamRoleStatements:
#     - Effect: 'Allow'
#       Action:
#         - 's3:*'
#       Resource:
#         - 'arn:aws:s3:::punj-bucket'
#         - 'arn:aws:s3:::punj-bucket/*'

# functions:
#   app:
#     handler: app.handler
#     events:
#       - http:
#           path: /app
#           method: ANY
service: sample-app

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

functions:
  hello:
    handler: app.handler
    events:
      - http:
          path: /dashboard
          method: any
      - http:
          path: /{execution+} # this matches any path, the token 'any' doesn't mean anything special
          method: any
